name: The Other 12 Hours
favicon: null
layout_spectrum: 0.89039
typography_spectrum: 0.30902
title: Outside of normal working hours
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.7707620526198298
  lightness: 0.1450511331204325
  saturation: 0.7144530820660293
  rhythmicContrast: 0.13086883001960814
purpose: []
