name: The Other 12 Hours
favicon: null
layout_spectrum: 0.99746
typography_spectrum: 0.37996
title: Outside of normal working hours
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fc4349'
    - '#6dbcdb'
    - '#d7dadb'
    - '#2c3e50'
    - '#ffffff'
  brandStrength: 1
  lightness: 0.375
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
