name: The Other 12 Hours
favicon: null
layout_spectrum: 1
typography_spectrum: 0.41787
title: Outside of normal working hours
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fc4349'
    - '#6dbcdb'
    - '#d7dadb'
    - '#2c3e50'
    - '#ffffff'
  brandStrength: 0.625
  lightness: 0.1450511331204325
  saturation: 0.875
  rhythmicContrast: 0.13086883001960814
purpose: []
